/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as EventsSlugRouteImport } from './routes/events_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events_/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/rules': typeof RulesRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/rules': typeof RulesRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/rules': typeof RulesRoute
  '/events_/$slug': typeof EventsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/events' | '/gallery' | '/rules' | '/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/events' | '/gallery' | '/rules' | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/events'
    | '/gallery'
    | '/rules'
    | '/events_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  RulesRoute: typeof RulesRoute
  EventsSlugRoute: typeof EventsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$slug': {
      id: '/events_/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  RulesRoute: RulesRoute,
  EventsSlugRoute: EventsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
